general:
  start: "2015-01-01 00:00:00"
  end: "2015-12-31 23:45:00"
  timebase: 15
  time_freq: "15min"
  latitude: 50.941357
  longitude: 6.958307
  name: "VPP"
  output_file: "./output/loadshape.csv"
  pv_data_file: "./input/pv/dwd_pv_data_2015.csv"
  slp_data_file: "./input/baseload/SLP_Amprion_15min_kW.csv"
  baseload_file_vpplib: "./input/baseload/df_S_15min.csv"
  mean_temp_days: "./input/thermal/dwd_temp_days_2015.csv"
  mean_temp_hours: "./input/thermal/dwd_temp_hours_2015.csv"
  mean_temp_15min: "./input/thermal/dwd_temp_15min_2015.csv"
  market_data: "./input/market_data/market_data.csv"
  t_0: 40

optimization:
  optimizer: "cost" # cost or co2
  dynamic_tariff: True
  dynamic_grid_cost: True
  grid_fee_high: 10.34 # ct/kWh
  grid_fee_low: 1.73 # ct/kWh
  grid_fee_standard: 5.77 # ct/kWh
  fixed_cost: 28 # ct/kWh, if dynamic tariff and/or dynamic_grid_costs are true the fixed cost value will be added on top of dynamic prices
  fixed_feed_in: False # if False, feed in price will equal the spot price at the day ahead market
  fixed_feed_in_cost: 8 # ct/kWh, only if fixed feed in is True

actors:
- name: residential_building
  SLP_type: H00
  building_type: "DE_HMF34"
  yearly_electrical_energy_demand: 40000      # kWh/a inkl. HP-Strom
  yearly_thermal_energy_demand: 80000         # kWh_th/a
  P_pv_nom: 40                                # kWp
  E_bat_nom: 40                               # kWh
  P_bat_nom: 20                               # kW
  heating: HP_Ground
  P_hp_nom: 19                                # kW_el @ JAZ~3.5
  E_th_nom: 46                                # kWh_th (~2.0 m³ @ ΔT 20 K)

- name: commercial_building
  SLP_type: G00
  building_type: "DE_GKO34"
  yearly_electrical_energy_demand: 20000
  yearly_thermal_energy_demand: 30000
  P_pv_nom: 30
  E_bat_nom: 30
  P_bat_nom: 15
  heating: HP_Air
  P_hp_nom: 14                                  # kW_el @ JAZ~3.5
  E_th_nom: 23                                  # kWh_th (~1.0 m³ @ ΔT 20 K)


# Component speficifation:

heat_pumps:
  HP_Ground:
    type: Ground 
    cop: 4
    cop_at_minus10: 3.5
    temp: 55
    p_min: 0.25 # Mindestleistung wenn eingeschaltet in % der Nennleistung
  HP_Air:
    type: Air
    cop: 3
    cop_at_minus10: 2.5
    temp: 45
    p_min: 0.35 # Mindestleistung wenn eingeschaltet in % der Nennleistung

thermal_storage:
  standing_loss_per_day: 0.0052   # in %     
  c_water: 4.18                   # kJ/kg/K – optional, fix
  t_room: 18                      # Temperatur des Raumes, in dem Pufferspeicher installiert ist 
  HP_Air:
    t_min: 30
    t_max: 45
  HP_Ground:
    t_min: 35
    t_max: 55

pv_systems:
  module_lib: "SandiaMod"
  module: "Canadian_Solar_CS5P_220M___2009_"
  inverter_lib: "cecinverter"
  inverter: "Connect_Renewable_Energy__CE_4000__240V_"
  surface_tilt: 35
  surface_azimuth: 200
  modules_per_string: 4
  strings_per_inverter: 2
  temp_lib: "sapm"
  temp_model: "open_rack_glass_glass"

battery: # Huawei LUNA2000-200kWh-2H1
  initial_SoC: 0.5
  charge_efficiency: 0.98
  discharge_efficiency: 0.98
  max_power: 100
  capacity: 193.5 
  standing_loss: 5.2e-5 # ~ 0.5% pro Tag
  extendable: False  # not implemented yet
  capital_cost: 1000 # €/kWh  # not implemented yet
